### ISSUE TITLE
Users crashing due to max vehicle setting?

### ISSUE THREAD

**Issue by yolobrandon01** [enc0ded/enc0ded-persistent-vehicles#1]
I went to sleep after getting the resource running properly. I then woke up and shortly after about 9 hours and possibly even before i'm not sure. Users were crashing with this error. I have disabled the resource and it has stopped the crashing.

![image](https://user-images.githubusercontent.com/66453444/83831221-ef757d80-a6b4-11ea-85ac-2eb9c1d62f50.png)

**Comment by enc0ded** [comment]
I'll look into this today.

**Comment by enc0ded** [comment]
Fixed https://github.com/enc0ded/enc0ded-persistent-vehicles/commit/c72c0f21ff94c4d805cf17c29627c93ebfaf219e
