### ISSUE TITLE
error while encoding 'number'

### ISSUE THREAD

**Issue by UnlegitWolfHD** [enc0ded/enc0ded-persistent-vehicles#13]
I spawned 300 Vehicle on the Map (on different places)
and when i restart the server i become this error:

`SCRIPT ERROR: @enc0ded-persistent-vehicles/server/main.lua:247: error while encoding 'number'
> SavedPlayerVehiclesToFile (@enc0ded-persistent-vehicles/server/main.lua:247)
> handler (@enc0ded-persistent-vehicles/server/main.lua:37)
> fn (@enc0ded-persistent-vehicles/server/main.lua:413)`

https://prnt.sc/tru4bf

edit: all Vehicles are saved in the file

**Comment by enc0ded** [comment]
script no longer supported. Please use: https://fivem-mods.tebex.io/package/4499436
