### ISSUE TITLE
Does not save records to file

### ISSUE THREAD

**Issue by paulvilla** [enc0ded/enc0ded-persistent-vehicles#16]
I am using esx_advancevehicleshop and after trying to get it to work in the console it throws me this message
https://i.imgur.com/MQxRsz5.png

checked the cars file and i don't see any change:
https://i.imgur.com/wVCa1cs.png
.
I have added the following in the store:
https://i.imgur.com/aiZiKLr.png

could you tell me if it's okay?

**Comment by TyceTV** [comment]
@paulvilla
Where did you include this code?
`TriggerEvent('persistent-vehicles/save-vehicles-to-file')`
The vehicles are only written to the file when this event is triggered!

If you are using ESX, look for the code in: es_extended/server/functions.lua

```
ESX.StartDBSync = function()
	function saveData()
```

insert: example->
```

ESX.StartDBSync = function()
	function saveData()
		ESX.SavePlayers()
		SetTimeout(5 * 60 * 1000, saveData)
		TriggerEvent('persistent-vehicles/save-vehicles-to-file')
	end

	SetTimeout(5 * 60 * 1000, saveData)
end
```

**Comment by Gregory-Hepicloud** [comment]
we have same issue 

we have add line to startdbsync and try 'pv-save-to-file'

console log with print : 

`pv-save-to-file
{"ZBY 531":{"entity":150075,"pos":{"y":-773.9736328125,"z":29.970703125,"r":{"y":-0.10593966394662857,"z":69.64142608642578,"x":0.3602737486362457},"h":69.64142608642578,"x":226.0087890625},"props":{"bodyHealth":"174.0","neonEnabled":[false,false,false,false],"engineHealth":"803.25830078125","wheels":5,"pearlescentColor":5,"interiorColor":111,"plate":"ZBY 531","rgbcolor1":[8,8,8],"plateIndex":0,"dirtLevel":"4.8000001907349","engine":false,"locked":0,"wheelColor":112,"tyreSmokeColor":[255,255,255],"extras":[],"xenonColor":255,"color2":4,"color1":0,"model":1549126457,"rgbcolor2":[90,94,102],"fuelLevel":"32.80004119873","neonColor":[255,0,255]}}}
Persistent Vehicles: 1 vehicles saved to file`

but file is empty

**Comment by enc0ded** [comment]
script no longer supported. Please use: https://fivem-mods.tebex.io/package/4499436
