### ISSUE TITLE
props error

### ISSUE THREAD

**Issue by xrtw** [enc0ded/enc0ded-persistent-vehicles#17]
everytime when take vehicle, get props error. using extendedmode. 
https://i.gyazo.com/1fae2157d9dbf5a48b2d2ef071e0ace5.png
https://i.gyazo.com/9b5d078087f0ce8fdf6ffc5696524b62.png

**Comment by xXcarlos117Xx2** [comment]
This happens to me too, please update with the solution, do not close like that!
