### ISSUE TITLE
`Persistent Vehicles: Waited too long for the clients to respawn vehicles´

### ISSUE THREAD

**Issue by Rassez** [enc0ded/enc0ded-persistent-vehicles#2]
Hello. So i'm not sure, but sometimes i got this message: 
_**Persistent Vehicles: Waited too long for the clients to respawn vehicles**_

Basicly, if i saved example three car around map, restart server and and join back to server. Other two car got deleted, but latest vehicle duplicates three times. I'm not sure what cause it.

![photo](https://user-images.githubusercontent.com/50022415/83875930-af5bdc80-a740-11ea-9f2c-9bd2ae7f0d3b.png)

**Comment by enc0ded** [comment]
Fixed: https://github.com/enc0ded/enc0ded-persistent-vehicles/commit/6b61932550e98b0503702e1c8f86145566d91089
