### ISSUE TITLE
Vehicle's not repopping

### ISSUE THREAD

**Issue by lt9nine** [enc0ded/enc0ded-persistent-vehicles#4]
So my problem is not that the basic repopping doesnt work. The main problem is, that we have 2 main Server-Restarts. One in the early morning, and one in the evening. So If I park my Vehicle at night in front of my house, I leave and it won't get repopulated because noone is in the area if my vehicle, it won't save to the file and at the Restart in the evening it's gone.
Is there any solution?

Ty btw for this great script

**Comment by enc0ded** [comment]
save vehicle to file needs to happen before server restarts.
