### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by GiroudMathias** [enc0ded/enc0ded-persistent-vehicles#8]
In some cases, which I can't describe at the moment, it appears that the vehicles that are managed by the persistence script are duplicated
https://media.discordapp.net/attachments/702494756760059904/721644153120751686/unknown.png
https://media.discordapp.net/attachments/702494756760059904/721644090244071434/unknown.png
https://media.discordapp.net/attachments/702494756760059904/721643961235669122/unknown.png

**Comment by enc0ded** [comment]
which version of FiveM and this script?

**Comment by Livvux** [comment]
I can confirm this

**Comment by ShadowOfVoid** [comment]
it happend to me also , FxV : 2654 and latest Version of script - funny thing is sometimes when i join to my server , two cars just appear in top of me ! which shouldnt be there at all !

**Comment by enc0ded** [comment]
Seems like somewhere around version 2500 it breaks this mod. Stick to optional version 2443.

**Comment by GiroudMathias** [comment]
After several tests, it seems that the problem occurs when a player with a very weak connection (a lot of FPS) connects / arrives in the area.
I think that the latency causes a "loop" that makes the vehicle appear several times.

**Comment by JamsRepos** [comment]
> Seems like somewhere around version 2500 it breaks this mod. Stick to optional version 2443.

Sticking to this version causes it's own issues now. Is there any plans to fix or should we stop using this?

**Comment by FilipeQ** [comment]
I have the same problem. Sometimes duplicated cars are created. Do you have any fix for this problem?

**Comment by enc0ded** [comment]
script no longer supported. Please use: https://fivem-mods.tebex.io/package/4499436
